FROM centos

RUN yum install ruby -y

#This step will be done on your podman/docker host once you have already set up local git repo using "https://mojo.redhat.com/docs/DOC-1042241" only then COPY will work

WORKDIR /verification-tests/

COPY ./verification/ .

WORKDIR /verification-tests/verification-tests/tools

RUN ./install_os_deps.sh

RUN ./hack_bundle.rb

RUN bundle update

WORKDIR /verification-tests/verification-tests/

CMD ["/bin/bash"]

